[project]
name = 'Decentralized-Water-Rights-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.water-rights]
path = 'contracts/water-rights.clar'
clarity_version = 2
epoch = 2.5

[contracts.water-source]
path = 'contracts/water-source.clar'
clarity_version = 2
epoch = 2.5

[contracts.water-trading]
path = 'contracts/water-trading.clar'
clarity_version = 2
epoch = 2.5

[contracts.water-usage]
path = 'contracts/water-usage.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
